[project]
name = "hass-aidot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "homeassistant>=2025.8.0",
    "python-aidot",
]

[tool.uv.sources]
python-aidot = { path = "../python-aidot" }
